services:
  sensor_addresses_db:
    build:
      context: ./sensor
      target: postgres_sensor
    image: postgres_sensor
    container_name: sensor_addresses_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  sensor:
    build:
      context: ./sensor
      target: sensor
    image: sensor
    container_name: sensor
    ports:
      - "8080:8080"
    command: python app.py sensor 8080 sensor_type_one
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      - sensor_addresses_db

  sensor2:
    image: sensor
    container_name: sensor2
    ports:
      - "8081:8081"
    command: python app.py sensor2 8081 sensor_type_two
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      - sensor_addresses_db

  sensor3:
    image: sensor
    container_name: sensor3
    ports:
      - "8082:8082"
    command: python app.py sensor3 8082 sensor_type_three
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      - sensor_addresses_db

  sensor4:
    image: sensor
    container_name: sensor4
    ports:
      - "8083:8083"
    command: python app.py sensor4 8083 sensor_type_four
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      - sensor_addresses_db

  sensor5:
    image: sensor
    container_name: sensor5
    ports:
      - "8084:8084"
    command: python app.py sensor5 8084 sensor_type_five
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      - sensor_addresses_db

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/appdata/influxdb2/config:/etc/influxdb2
      - ./data/appdata/influxdb2/db:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb
      - DOCKER_INFLUXDB_INIT_ORG=collsense
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=832@#9870232#834

  collector:
    build: .
    image: collector:latest
    container_name: collector
    environment:
      - INFLUXDB_TOKEN=832@#9870232#834
      - DB_PASSWORD=postgres
    ports:
      - "800:800"
    volumes:
      - ./data/db/test:/test
    depends_on:
      - influxdb
      - sensor
      - sensor2
      - sensor3
      - sensor4
      - sensor5
      - sensor_addresses_db